#Configuracion
#Mon May 11 11:19:41 MST 2026
registration.image.last.directory=C\:\\Users\\DASC\\Desktop
registration.window.height=500
registration.window.width=500
registration.window.x=2238
registration.window.y=103
ui.theme=light
users.export.pdf=C\:\\Users\\DASC\\Desktop\\2026-I\\Programaci\u00F3n 3 IDS TM
